### ISSUE TITLE
CameraXBasic Sample looks horrible on Pixel C tablet

### ISSUE THREAD

**Issue by vntodorova** [android/camera#52]
Tablet model: Pixel C
Android Version: 8.1.0
CameraX Version: 1.0.0-alpha03

Here is a screenshot of how the camera in the CameraXBasic sample looks like after I build and run it.

![Screenshot_20190815-124813](https://user-images.githubusercontent.com/12056488/63087815-bb7d7000-bf5b-11e9-9d04-5bf3a2feff45.png)

I tested it on other tablets and it looks good.

**Comment by owahltinez** [comment]
Thanks for reporting @vntodorova. We have a lot of work to do around different layout sizes, since this affects e.g. Chromebooks as well. Unfortunately, the library is currently focused only on phone form factors at the moment but we will likely revisit this in the future (likely after the library reaches the beta milestone)
